package TransferApp;


/**
* TransferApp/BytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public final class BytesHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public BytesHolder ()
  {
  }

  public BytesHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransferApp.BytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransferApp.BytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransferApp.BytesHelper.type ();
  }

}
