package TransferApp;


/**
* TransferApp/PathListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public final class PathListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PathListHolder ()
  {
  }

  public PathListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransferApp.PathListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransferApp.PathListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransferApp.PathListHelper.type ();
  }

}
