package TransferApp;

/**
* TransferApp.PathListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Saturday, October 12, 2019 3:43:57 PM BRT
*/

public final class PathListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PathListHolder ()
  {
  }

  public PathListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PathListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PathListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PathListHelper.type ();
  }

}
