package TransferApp;


/**
* TransferApp/TransferHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Quarta-feira, 2 de Outubro de 2019 22h02min26s GFT
*/

abstract public class TransferHelper
{
  private static String  _id = "IDL:TransferApp/Transfer:1.0";

  public static void insert (org.omg.CORBA.Any a, TransferApp.Transfer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TransferApp.Transfer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TransferApp.TransferHelper.id (), "Transfer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TransferApp.Transfer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TransferStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TransferApp.Transfer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TransferApp.Transfer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TransferApp.Transfer)
      return (TransferApp.Transfer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TransferApp._TransferStub stub = new TransferApp._TransferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TransferApp.Transfer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TransferApp.Transfer)
      return (TransferApp.Transfer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TransferApp._TransferStub stub = new TransferApp._TransferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
