package TransferApp;

/**
* TransferApp/TransferP2PHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public final class TransferP2PHolder implements org.omg.CORBA.portable.Streamable
{
  public TransferApp.TransferP2P value = null;

  public TransferP2PHolder ()
  {
  }

  public TransferP2PHolder (TransferApp.TransferP2P initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransferApp.TransferP2PHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransferApp.TransferP2PHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransferApp.TransferP2PHelper.type ();
  }

}
