package TransferApp;

/**
* TransferApp/Transfer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Saturday, October 12, 2019 4:25:20 PM BRT
*/

public interface Transfer extends TransferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transfer
