package TransferApp;


/**
* TransferApp/TransferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 15h11min00s GFT
*/

public interface TransferOperations 
{
  String transfer (String file1);
  boolean enviarListaDeArquivos (String user, String[] list);
  boolean login (String user);
  void logout (String user);
  TransferApp.UserFiles[] requisitarListaDeArquivosComUser ();
  String[] requisitarListaDeArquivos (String user);
  void shutdown ();
} // interface TransferOperations
