package TransferApp;


/**
* TransferApp/TransferP2PPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public abstract class TransferP2PPOA extends org.omg.PortableServer.Servant
 implements TransferApp.TransferP2POperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("downloadFile", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TransferApp/TransferP2P/downloadFile
       {
         String fileName = in.read_string ();
         byte $result[] = null;
         $result = this.downloadFile (fileName);
         out = $rh.createReply();
         TransferApp.BytesHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TransferApp/TransferP2P:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TransferP2P _this() 
  {
    return TransferP2PHelper.narrow(
    super._this_object());
  }

  public TransferP2P _this(org.omg.CORBA.ORB orb) 
  {
    return TransferP2PHelper.narrow(
    super._this_object(orb));
  }


} // class TransferP2PPOA
