package TransferApp;


/**
* TransferApp/TransferP2P.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public interface TransferP2P extends TransferP2POperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TransferP2P
