package TransferApp;


/**
* TransferApp/TransferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Saturday, October 12, 2019 3:43:57 PM BRT
*/

public interface TransferOperations 
{
  String transfer (String file1);
  boolean enviarListaDeArquivos (String user, String[] list);
  void shutdown ();
} // interface TransferOperations
