package TransferApp;


/**
* TransferApp/Transfer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 15h11min00s GFT
*/

public interface Transfer extends TransferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Transfer
