package TransferApp;


/**
* TransferApp/TransferP2POperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public interface TransferP2POperations 
{
  byte[] downloadFile (String fileName);
} // interface TransferP2POperations
