package TransferApp;

/**
* TransferApp/TransferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 15h11min00s GFT
*/

public final class TransferHolder implements org.omg.CORBA.portable.Streamable
{
  public TransferApp.Transfer value = null;

  public TransferHolder ()
  {
  }

  public TransferHolder (TransferApp.Transfer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransferApp.TransferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransferApp.TransferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransferApp.TransferHelper.type ();
  }

}
