package TransferApp;


/**
* TransferApp/TransferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Quarta-feira, 2 de Outubro de 2019 22h02min26s GFT
*/

public interface TransferOperations 
{
  String transfer (String file1);
  void shutdown ();
} // interface TransferOperations
