package TransferApp;


/**
* TransferApp/UsersWithFilesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 18h44min21s GFT
*/

public final class UsersWithFilesHolder implements org.omg.CORBA.portable.Streamable
{
  public TransferApp.UserFiles value[] = null;

  public UsersWithFilesHolder ()
  {
  }

  public UsersWithFilesHolder (TransferApp.UserFiles[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TransferApp.UsersWithFilesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TransferApp.UsersWithFilesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TransferApp.UsersWithFilesHelper.type ();
  }

}
