package TransferApp;


/**
* TransferApp/UserFiles.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Transfer.idl
* Segunda-feira, 14 de Outubro de 2019 15h11min00s GFT
*/

public final class UserFiles implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String files[] = null;

  public UserFiles ()
  {
  } // ctor

  public UserFiles (String _name, String[] _files)
  {
    name = _name;
    files = _files;
  } // ctor

} // class UserFiles
